inherit_gem:
  rubocop-config-timedia:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml
    - config/factory_bot.yml

require:
  - rubocop-erb

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2
  Exclude:
    - .irbrc
    - bin/**/*
    - config/*
    - config/environments/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - public/**/*

Style/EmptyMethod:
  EnforcedStyle: expanded

# aggregate_failures をデフォルトで有効化するため、一つのexampleに複数のexpectationを記述することを許容する。
RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4
  Include:
    - spec/models/*
